### ISSUE TITLE
Seeding the database fails

### ISSUE THREAD

**Issue by tramuntanal** [decidim/decidim-initiatives#88]
# This is a (Bug Report)

#### :tophat: Description
When installing a project with decidim-initiatives `db:seed` fails.

For bug reports:
* What went wrong?
Something related with participatory spaces.
* What did you expect should have happened?
Seeding should work out of the box.
* What was the config you used?
Standard.
* What stacktrace or error message from your provider did you see?
```
== 20171219094405 MigrateOldResults: migrating ================================
== 20171219094405 MigrateOldResults: migrated (0.0005s) =======================

rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "decidim_initiatives_types" does not exist
LINE 8:                WHERE a.attrelid = '"decidim_initiatives_type...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"decidim_initiatives_types"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/home/oliver/prog/customers/decidim/decidim-initiatives/lib/decidim/initiatives/participatory_space.rb:13:in `block (3 levels) in <top (required)>'
/home/oliver/prog/customers/decidim/decidim-initiatives/lib/decidim/initiatives/participatory_space.rb:12:in `times'
/home/oliver/prog/customers/decidim/decidim-initiatives/lib/decidim/initiatives/participatory_space.rb:12:in `block (2 levels) in <top (required)>'
/home/oliver/prog/customers/decidim/initiatives_app/db/seeds.rb:9:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
PG::UndefinedTable: ERROR:  relation "decidim_initiatives_types" does not exist
LINE 8:                WHERE a.attrelid = '"decidim_initiatives_type...
                                          ^
/home/oliver/prog/customers/decidim/decidim-initiatives/lib/decidim/initiatives/participatory_space.rb:13:in `block (3 levels) in <top (required)>'
/home/oliver/prog/customers/decidim/decidim-initiatives/lib/decidim/initiatives/participatory_space.rb:12:in `times'
/home/oliver/prog/customers/decidim/decidim-initiatives/lib/decidim/initiatives/participatory_space.rb:12:in `block (2 levels) in <top (required)>'
/home/oliver/prog/customers/decidim/initiatives_app/db/seeds.rb:9:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***: localhost/development
* ***Browser & version***:
* ***Screenshot***:
* ***Error messages***: ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "decidim_initiatives_types" does not exist
* ***URL to reproduce the error***:
Install the project, bundle install, configure the database and `bin/rails db:create db:migrate db:seed`.

**Comment by tramuntanal** [comment]
My fault forgot to run `rake decidim:upgrade` before migrating. :/
